export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'Edge computing cloud native project:OpenYurt',
        author: '郭飞，徙远，新胜',
        dateStr: 'May 29，2020',
        desc: 'introduce of OpenYurt, including generation background, technical characteristics, core competence, road map',
        link: '/zh-cn/blog/introduce_of_OpenYurt.html',
      },
      {
        title: 'Yurtctl: make the native k8s cluster achieve edge computing capabilities',
        author: '郑超',
        dateStr: 'June 6，2020',
        desc: 'How to use the command line management tool Yurtctl provided by OpenYurt to efficiently and quickly deploy OpenYurt cluster.',
        link: '/zh-cn/blog/use_of_yurtctl.html',
      },
      {
        title: 'Getting Started with OpenYurt: Play with OpenYurt on Raspberry Pi',
        author: '唐炳昌',
        dateStr: 'January 1，2021',
        desc: 'By deploying the control plane of the Kubernetes cluster in the cloud and connecting the Raspberry Pi to the cluster to build a cloud management side scene,demonstrate the core capabilities of OpenYurt',
        link: '/zh-cn/blog/Play_with_Openyurt_on_Raspberry_Pi.html',
      },
      {
        title: 'Edge autonomy of OpenYurt: YurtHub Design Detail',
        author: '新胜',
        dateStr: 'June 18，2020',
        desc: 'introduce of edge autonomy and the design detail about YurtHub that realizes the edge autonomy of OpenYurt',
        link: '/zh-cn/blog/YurtHub_Design_Detail.html',
      },
      {
        title: 'Viewing Expansion Ability of YurtHub from Edge Autonomy',
        author: '新胜',
        dateStr: 'June 29，2020',
        desc: 'Focus on the expansion capabilities of YurtHub: 1) Edge network autonomy; 2) Multi-cloud address support; 3) Cloud flow control in the node dimension; 4) Node certificate rotation management',
        link: '/zh-cn/blog/Expansion_Capability_of_Yurthub.html',
      },
      {
        title: 'How Openyurt runs the business pod in edge scenarios',
        author: '新胜',
        dateStr: 'Oct 15，2021',
        desc: 'Seamlessly run business Pods using InClusterConfig in edge scenarios',
        link: '/zh-cn/blog/How_run_business_pod_in_edge_scenarios.html',
      },
      {
        title: 'Elegant realization of edge gateway caching capabilities',
        author: '新胜',
        dateStr: 'Mar 29，2021',
        desc: 'the introduce about how OpenYurt solves the problem of edge autonomy',
        link: '/zh-cn/blog/Elegant_realization_of_edge_gateway_caching_capabilities.html',
      },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: '边缘计算云原生项目OpenYurt',
        author: '郭飞，徙远，新胜',
        dateStr: 'May 29，2020',
        desc: 'OpenYurt介绍，包括诞生背景，技术特点，核心能力，发展路线',
        link: '/zh-cn/blog/introduce_of_OpenYurt.html',
      },
      {
        title: 'OpenYurt 开箱测评 | 一键让原生 K8s 集群具备边缘计算能力',
        author: '郑超',
        dateStr: 'June 6，2020',
        desc: '如何使用 OpenYurt 提供的命令行管理工具 Yurtctl， 高效快速地部署 OpenYurt 集群',
        link: '/zh-cn/blog/use_of_yurtctl.html',
      },
      {
        title: '入门OpenYurt: 在树莓派上玩转OpenYurt',
        author: '唐炳昌',
        dateStr: 'January 1，2021',
        desc: '通过在云端部署 Kubernetes 集群的控制面，并将树莓派接入集群来搭建云管边场景,来演示 OpenYurt 的核心能力',
        link: '/zh-cn/blog/Play_with_Openyurt_on_Raspberry_Pi.html',
      },
      {
        title: 'OpenYurt边缘自治能力的设计细节:YurtHub',
        author: '新胜',
        dateStr: 'June 18，2020',
        desc: '介绍边缘自治特性以及OpenYurt实现边缘自治的设计细节',
        link: '/zh-cn/blog/YurtHub_Design_Detail.html',
      },
      {
        title: '从边缘自治看YurtHub的扩展能力',
        author: '新胜',
        dateStr: 'June 29，2020',
        desc: '主要介绍了YurtHub的扩展能力: 1) 边缘网络自治; 2) 多云端地址支持; 3) 节点维度的流量控制; 4) 节点证书轮换管理',
        link: '/zh-cn/blog/Expansion_Capability_of_Yurthub.html',
      },
      {
        title: '边缘场景下，Openyurt如何无缝运行业务Pod',
        author: '新胜',
        dateStr: 'Oct 15，2021',
        desc: 'OpenYurt: 在边缘场景无缝运行使用InClusterConfig的业务Pod',
        link: '/zh-cn/blog/How_run_business_pod_in_edge_scenarios.html',
      },
      {
        title: '边缘网关缓存能力的优雅实现',
        author: '新胜',
        dateStr: 'Mar 29，2021',
        desc: '1）OpenYurt如何解决边缘自治问题；2）YurtHub的实现',
        link: '/zh-cn/blog/Elegant_realization_of_edge_gateway_caching_capabilities.html',
      },
    ],
  },
};
